services:
    PacificaSearchBundle\Service\SearchService:
        arguments: ["%elasticsearch_host%", "%elasticsearch_index%"]

    PacificaSearchBundle\Repository\InstrumentTypeRepository:
        arguments: ["@PacificaSearchBundle\\Service\\SearchService"]
    PacificaSearchBundle\Repository\InstrumentRepository:
        arguments: ["@PacificaSearchBundle\\Service\\SearchService"]
    PacificaSearchBundle\Repository\InstitutionRepository:
        arguments: ["@PacificaSearchBundle\\Service\\SearchService"]
    PacificaSearchBundle\Repository\UserRepository:
        arguments: ["@PacificaSearchBundle\\Service\\SearchService"]
    PacificaSearchBundle\Repository\ProposalRepository:
        arguments: ["@PacificaSearchBundle\\Service\\SearchService"]