services:
    PacificaSearchBundle\Repository\FilterResultsRepository: ~

#    pacifica_search.example:
#        class: PacificaSearchBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
