services:
    PacificaSearchBundle\Service\SearchService:
        arguments: ["%elasticsearch_host%", "%elasticsearch_index%"]

    PacificaSearchBundle\Repository\InstrumentTypeRepository:
        arguments: ["@PacificaSearchBundle\\Service\\SearchService"]